# Generated by Django 5.2 on 2025-08-30 20:14

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("cpf_cnpj", models.CharField(max_length=18, unique=True)),
                ("endereco", models.TextField(blank=True, null=True)),
                ("telefone", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="EmpresaTerceira",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("cpf_cnpj", models.CharField(max_length=18, unique=True)),
                ("endereco", models.TextField(blank=True, null=True)),
                ("telefone", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("informacoes_bancarias", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "grupo",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("coordenador", "Coordenador de Contrato"),
                            ("gerente", "Gerente"),
                            ("diretoria", "Diretoria"),
                            ("financeiro", "Financeiro"),
                            ("comercial", "Comercial"),
                            ("terceiro", "Terceiro"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "centro",
                    models.CharField(
                        choices=[("SUS", "Sustentabilidade"), ("SAN", "Saneamento")],
                        max_length=30,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True, related_name="+", to="auth.group"
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True, related_name="+", to="auth.permission"
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Contrato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cod_projeto", models.CharField(max_length=50, unique=True)),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField()),
                ("valor_total", models.DecimalField(decimal_places=2, max_digits=12)),
                ("objeto", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("em_elaboracao", "Em elaboração"),
                            ("aguardando_assinatura", "Aguardando assinatura"),
                            ("ativo", "Ativo"),
                            ("suspenso", "Suspenso"),
                            ("encerrado", "Encerrado"),
                        ],
                        default="em_elaboracao",
                        max_length=30,
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestao_contratos.cliente",
                    ),
                ),
                (
                    "coordenador",
                    models.ForeignKey(
                        limit_choices_to={"groups__name": "Coordenador de Contrato"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contratos_cliente_coordenados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Aditivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.TextField()),
                ("motivo", models.TextField(blank=True, null=True)),
                (
                    "valor_adicional",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("nova_data_fim", models.DateField(blank=True, null=True)),
                ("data_registro", models.DateField(default=django.utils.timezone.now)),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aditivos",
                        to="gestao_contratos.contrato",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContratoTerceiros",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField()),
                ("valor_total", models.DecimalField(decimal_places=2, max_digits=12)),
                ("objeto", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("em_elaboracao", "Em elaboração"),
                            ("aguardando_assinatura", "Aguardando assinatura"),
                            ("ativo", "Ativo"),
                            ("suspenso", "Suspenso"),
                            ("encerrado", "Encerrado"),
                        ],
                        default="em_elaboracao",
                        max_length=30,
                    ),
                ),
                (
                    "cod_projeto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestao_contratos.contrato",
                    ),
                ),
                (
                    "coordenador",
                    models.ForeignKey(
                        limit_choices_to={"groups__name": "Coordenador de Contrato"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contratos_coordenados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa_terceira",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestao_contratos.empresaterceira",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_bm", models.PositiveIntegerField()),
                (
                    "valor_pago",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("parcela_paga", models.PositiveIntegerField()),
                ("data_pagamento", models.DateField(default=django.utils.timezone.now)),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boletins_medicao",
                        to="gestao_contratos.contratoterceiros",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AditivoTerceiro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.TextField()),
                ("motivo", models.TextField(blank=True, null=True)),
                (
                    "valor_adicional",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("nova_data_fim", models.DateField(blank=True, null=True)),
                ("data_registro", models.DateField(default=django.utils.timezone.now)),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aditivos",
                        to="gestao_contratos.contratoterceiros",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContratoTimeline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("etapa", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True, null=True)),
                ("data", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline",
                        to="gestao_contratos.contrato",
                    ),
                ),
            ],
            options={
                "ordering": ["data"],
            },
        ),
        migrations.CreateModel(
            name="ContratoTimelineTerceiro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("etapa", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True, null=True)),
                ("data", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline",
                        to="gestao_contratos.contratoterceiros",
                    ),
                ),
            ],
            options={
                "ordering": ["data"],
            },
        ),
        migrations.CreateModel(
            name="DocumentoContrato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("arquivo", models.FileField(upload_to="contratos/documentos/")),
                ("descricao", models.CharField(blank=True, max_length=200, null=True)),
                ("data_envio", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="gestao_contratos.contrato",
                    ),
                ),
                (
                    "enviado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documentos_contrato_enviados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DocumentoContratoTerceiro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "arquivo",
                    models.FileField(upload_to="contratos/documentos_terceiros/"),
                ),
                ("descricao", models.CharField(blank=True, max_length=200, null=True)),
                ("data_envio", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos_terceiros",
                        to="gestao_contratos.contratoterceiros",
                    ),
                ),
                (
                    "enviado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documentos_contrato_terceiro_enviados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AvaliacaoFornecedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("area_avaliadora", models.CharField(max_length=100)),
                (
                    "nota",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("comentario", models.TextField(blank=True, null=True)),
                ("data_avaliacao", models.DateField(auto_now_add=True)),
                (
                    "contrato_terceiro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestao_contratos.contratoterceiros",
                    ),
                ),
                (
                    "empresa_terceira",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestao_contratos.empresaterceira",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EntregaFornecedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "arquivo",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="produto_do_fornecedor/",
                        verbose_name="Inserir arquivo para comprovação de entrega",
                    ),
                ),
                ("justificativa", models.TextField(blank=True, null=True)),
                (
                    "avaliacao",
                    models.CharField(
                        blank=True,
                        choices=[("Aprovado", "Aprovado"), ("Reprovado", "Reprovado")],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("data_prevista", models.DateField(blank=True, null=True)),
                ("data_entrega", models.DateField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contrato_terceiro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestao_contratos.contratoterceiros",
                    ),
                ),
                (
                    "empresa_terceira",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestao_contratos.empresaterceira",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Indicadores",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "empresa_terceira",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestao_contratos.empresaterceira",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Proposta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(max_length=50, unique=True)),
                ("descricao", models.TextField()),
                ("valor_total", models.DecimalField(decimal_places=2, max_digits=12)),
                ("data_envio", models.DateField(default=django.utils.timezone.now)),
                ("prazo_validade", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("analise", "Em análise"),
                            ("aprovada", "Aprovada"),
                            ("reprovada", "Reprovada"),
                        ],
                        default="analise",
                        max_length=20,
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestao_contratos.cliente",
                    ),
                ),
                (
                    "responsavel_comercial",
                    models.ForeignKey(
                        limit_choices_to={"groups__name": "Comercial"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="propostas_comerciais",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "responsavel_tecnico",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="propostas_tecnicas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="contrato",
            name="proposta",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="gestao_contratos.proposta",
            ),
        ),
        migrations.CreateModel(
            name="PropostaTerceiro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(max_length=50, unique=True)),
                ("descricao", models.TextField()),
                ("valor_total", models.DecimalField(decimal_places=2, max_digits=12)),
                ("condicoes_pagamento", models.CharField(max_length=200)),
                ("data_envio", models.DateField(default=django.utils.timezone.now)),
                ("prazo_validade", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("analise", "Em análise"),
                            ("aprovada", "Aprovada"),
                            ("reprovada", "Reprovada"),
                        ],
                        default="analise",
                        max_length=20,
                    ),
                ),
                (
                    "orcamento_pdf",
                    models.FileField(
                        upload_to="orcamentos/", verbose_name="Inserir Orçamento PDF"
                    ),
                ),
                (
                    "empresa_terceira",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestao_contratos.empresaterceira",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SolicitacaoContratacaoTerceiro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "area_solicitante",
                    models.CharField(
                        choices=[
                            ("Inovação", "Inovação"),
                            ("Geotecnia", "Geotecnia"),
                            ("Recursos Hídricos", "Recursos Hídricos"),
                            ("Saneamento", "Saneamento"),
                            ("Sustentabilidade", "Sustentabilidade"),
                        ],
                        max_length=30,
                    ),
                ),
                ("justificativa", models.TextField(blank=True, null=True)),
                ("valor_vendido_ao_cliente", models.FloatField()),
                ("prazo_contratual", models.TextField()),
                ("inicio_contrato", models.DateField()),
                ("termino_contrato", models.DateField()),
                (
                    "indicacao_proposta_vencedora",
                    models.FileField(
                        upload_to="proposta_vencedora/",
                        verbose_name="Inserir indicação clara da proposta vencedora em PDF",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cod_projeto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="gestao_contratos.contrato",
                    ),
                ),
                (
                    "empresa_1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestao_contratos.empresaterceira",
                    ),
                ),
                (
                    "empresa_2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contratos_empresa_2",
                        to="gestao_contratos.empresaterceira",
                    ),
                ),
                (
                    "empresa_3",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contratos_empresa_3",
                        to="gestao_contratos.empresaterceira",
                    ),
                ),
                (
                    "numero_proposta_1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solicitacoes_como_proposta_1",
                        to="gestao_contratos.propostaterceiro",
                    ),
                ),
                (
                    "numero_proposta_2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="solicitacoes_como_proposta_2",
                        to="gestao_contratos.propostaterceiro",
                    ),
                ),
                (
                    "numero_proposta_3",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="solicitacoes_como_proposta_3",
                        to="gestao_contratos.propostaterceiro",
                    ),
                ),
                (
                    "responsavel_comercial",
                    models.ForeignKey(
                        limit_choices_to={"groups__name": "Comercial"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="solicitacoes_comerciais",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "solicitante_nome",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="solicitacoes_contratacao_terceiros",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="contratoterceiros",
            name="proposta",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="gestao_contratos.solicitacaocontratacaoterceiro",
            ),
        ),
    ]
