# Generated by Django 5.2 on 2025-09-05 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestao_contratos", "0002_alter_contrato_coordenador_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="solicitacaoprospeccao",
            name="status",
        ),
        migrations.AddField(
            model_name="solicitacaoprospeccao",
            name="aprovado",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="solicitacaoprospeccao",
            name="aprovado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="aprovacoes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="solicitacaoprospeccao",
            name="data_aprovacao",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
