# Generated by Django 5.2 on 2025-09-05 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestao_contratos", "0003_remove_solicitacaoprospeccao_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitacaoprospeccao",
            name="fornecedores_selecionados",
            field=models.ManyToManyField(
                blank=True, to="gestao_contratos.empresaterceira"
            ),
        ),
    ]
