# Generated by Django 5.2 on 2025-09-05 19:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestao_contratos", "0004_solicitacaoprospeccao_fornecedores_selecionados"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresaterceira",
            name="setor_de_atuacao",
            field=models.TextField(blank=True, null=True),
        ),
    ]
