# Generated by Django 5.2 on 2025-09-08 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestao_contratos", "0005_empresaterceira_setor_de_atuacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitacaoprospeccao",
            name="fornecedor_escolhido",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="escolhido_em",
                to="gestao_contratos.empresaterceira",
            ),
        ),
        migrations.AddField(
            model_name="solicitacaoprospeccao",
            name="nenhum_fornecedor_ideal",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="solicitacaoprospeccao",
            name="status",
            field=models.CharField(default="Em análise", max_length=100),
        ),
        migrations.AddField(
            model_name="solicitacaoprospeccao",
            name="triagem_realizada",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="TriagemFornecedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("selecionado", models.BooleanField(default=False)),
                (
                    "fornecedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestao_contratos.empresaterceira",
                    ),
                ),
                (
                    "solicitacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="triagens",
                        to="gestao_contratos.solicitacaoprospeccao",
                    ),
                ),
            ],
        ),
    ]
