# Generated by Django 5.2 on 2025-09-09 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "gestao_contratos",
            "0006_solicitacaoprospeccao_fornecedor_escolhido_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="proposta",
            name="responsavel_comercial",
        ),
        migrations.RemoveField(
            model_name="solicitacaocontratacaoterceiro",
            name="responsavel_comercial",
        ),
        migrations.AddField(
            model_name="proposta",
            name="responsavel_sumprimento",
            field=models.ForeignKey(
                limit_choices_to={"groups__name": "Suprimento"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="propostas_comerciais",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="solicitacaocontratacaoterceiro",
            name="responsavel_sumprimento",
            field=models.ForeignKey(
                limit_choices_to={"groups__name": "Suprimento"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="solicitacoes_comerciais",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="grupo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("coordenador", "Coordenador de Contrato"),
                    ("gerente", "Gerente"),
                    ("diretoria", "Diretoria"),
                    ("financeiro", "Financeiro"),
                    ("sumprimento", "Sumprimento"),
                    ("terceiro", "Terceiro"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
