# Generated by Django 5.2 on 2025-09-09 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestao_contratos", "0007_remove_proposta_responsavel_comercial_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PropostaFornecedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor_proposta",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("prazo_validade", models.DateField(blank=True, null=True)),
                (
                    "arquivo_proposta",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="orcamentos/",
                        verbose_name="Inserir Orçamento PDF",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "fornecedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestao_contratos.empresaterceira",
                    ),
                ),
                (
                    "solicitacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="propostas",
                        to="gestao_contratos.solicitacaoprospeccao",
                    ),
                ),
            ],
            options={
                "unique_together": {("solicitacao", "fornecedor")},
            },
        ),
        migrations.AlterField(
            model_name="solicitacaocontratacaoterceiro",
            name="numero_proposta_1",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="solicitacoes_como_proposta_1",
                to="gestao_contratos.propostafornecedor",
            ),
        ),
        migrations.AlterField(
            model_name="solicitacaocontratacaoterceiro",
            name="numero_proposta_2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="solicitacoes_como_proposta_2",
                to="gestao_contratos.propostafornecedor",
            ),
        ),
        migrations.AlterField(
            model_name="solicitacaocontratacaoterceiro",
            name="numero_proposta_3",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="solicitacoes_como_proposta_3",
                to="gestao_contratos.propostafornecedor",
            ),
        ),
        migrations.DeleteModel(
            name="PropostaTerceiro",
        ),
    ]
