# Generated by Django 5.2 on 2025-09-10 15:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gestao_contratos", "0008_propostafornecedor_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DocumentoContratoTerceiro",
        ),
    ]
