# Generated by Django 5.2 on 2025-09-10 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestao_contratos", "0009_delete_documentocontratoterceiro"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentoContratoTerceiro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_contrato", models.CharField(max_length=100, unique=True)),
                ("objeto", models.TextField()),
                ("prazo_inicio", models.DateField()),
                ("prazo_fim", models.DateField()),
                ("valor_total", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "arquivo_contrato",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="contratos/",
                        verbose_name="Contrato em PDF",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "solicitacao",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contrato_relacionado",
                        to="gestao_contratos.solicitacaoprospeccao",
                    ),
                ),
            ],
        ),
    ]
