# Generated by Django 5.2 on 2025-09-10 20:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestao_contratos", "0010_documentocontratoterceiro"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitacaoprospeccao",
            name="aprovacao_diretoria",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="solicitacaoprospeccao",
            name="aprovacao_gerencia",
            field=models.BooleanField(default=False),
        ),
    ]
