# Generated by Django 5.2 on 2025-09-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestao_contratos", "0011_solicitacaoprospeccao_aprovacao_diretoria_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitacaoprospeccao",
            name="acao_diretoria",
            field=models.CharField(
                blank=True,
                choices=[
                    ("renegociar_valor", "Renegociar Valor"),
                    ("renegociar_prazo", "Renegociar Prazo"),
                    ("alterar_fornecedor", "Selecionar outro Fornecedor"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="solicitacaoprospeccao",
            name="acao_gerencia",
            field=models.CharField(
                blank=True,
                choices=[
                    ("renegociar_valor", "Renegociar Valor"),
                    ("renegociar_prazo", "Renegociar Prazo"),
                    ("alterar_fornecedor", "Selecionar outro Fornecedor"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="solicitacaoprospeccao",
            name="justificativa_diretoria",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="solicitacaoprospeccao",
            name="justificativa_gerencia",
            field=models.TextField(blank=True, null=True),
        ),
    ]
