# Generated by Django 5.2 on 2025-09-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestao_contratos", "0012_solicitacaoprospeccao_acao_diretoria_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresaterceira",
            name="guarda_chuva",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="empresaterceira",
            name="ponto_focal",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
