# Generated by Django 5.2 on 2025-09-11 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestao_contratos", "0013_empresaterceira_guarda_chuva_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresaterceira",
            name="email_focal",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="empresaterceira",
            name="telefone_focal",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
