# Generated by Django 5.2 on 2025-09-11 19:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestao_contratos", "0014_empresaterceira_email_focal_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="propostafornecedor",
            name="condicao_pagamento",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Conforme Medição Aprovada", "Conforme Medição Aprovada"),
                    ("Conforme Pagamento do Cliente", "Conforme Pagamento do Cliente"),
                ],
                max_length=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="solicitacaoprospeccao",
            name="previsto_no_orcamento",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="solicitacaoprospeccao",
            name="valor_provisionado",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="solicitacaoprospeccao",
            name="valor_vendido",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
