# Generated by Django 5.2 on 2025-09-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestao_contratos", "0015_propostafornecedor_condicao_pagamento_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CentroDeTrabalho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=10, unique=True)),
                ("nome", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="user",
            name="centro",
        ),
        migrations.AddField(
            model_name="user",
            name="centro_antigo",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="propostafornecedor",
            name="condicao_pagamento",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Conforme Medição Aprovada", "Conforme Medição Aprovada"),
                    ("Conforme Pagamento do Cliente", "Conforme Pagamento do Cliente"),
                    ("A definir", "A definir"),
                ],
                max_length=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="centros",
            field=models.ManyToManyField(
                blank=True,
                related_name="usuarios",
                to="gestao_contratos.centrodetrabalho",
            ),
        ),
    ]
