# Generated by Django 5.2 on 2025-09-12 15:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gestao_contratos", "0016_centrodetrabalho_remove_user_centro_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="centro_antigo",
        ),
    ]
