# Generated by Django 5.2 on 2025-09-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestao_contratos", "0017_remove_user_centro_antigo"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitacaoprospeccao",
            name="reprovacao_gerencia",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="grupo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("coordenador", "Coordenador de Contrato"),
                    ("gerente", "Gerente"),
                    ("diretoria", "Diretoria"),
                    ("financeiro", "Financeiro"),
                    ("suprimento", "Suprimento"),
                    ("terceiro", "Terceiro"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
