# Generated by Django 5.2 on 2025-09-15 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestao_contratos", "0018_solicitacaoprospeccao_reprovacao_gerencia_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitacaoprospeccao",
            name="solicitacao_origem",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="revisoes",
                to="gestao_contratos.solicitacaoprospeccao",
            ),
        ),
    ]
