# Generated by Django 5.2 on 2025-09-18 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestao_contratos", "0019_solicitacaoprospeccao_solicitacao_origem"),
    ]

    operations = [
        migrations.AddField(
            model_name="bm",
            name="arquivo_bm",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="BM/",
                verbose_name="Inserir arquivo do Boletim de Medição",
            ),
        ),
        migrations.CreateModel(
            name="DocumentoBM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "minuta_boletim",
                    models.FileField(
                        blank=True, null=True, upload_to="Minuta boletim/"
                    ),
                ),
                (
                    "assinatura_fornecedor",
                    models.FileField(blank=True, null=True, upload_to="Assinaturas/"),
                ),
                (
                    "assinatura_gerente",
                    models.FileField(blank=True, null=True, upload_to="Assinaturas/"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "solicitacao",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestao_contratos.solicitacaoprospeccao",
                    ),
                ),
            ],
        ),
    ]
