# Generated by Django 5.2 on 2025-09-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestao_contratos", "0020_bm_arquivo_bm_documentobm"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitacaoprospeccao",
            name="requisitos",
            field=models.TextField(blank=True, null=True),
        ),
    ]
