# Generated by Django 5.2 on 2025-09-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestao_contratos", "0021_solicitacaoprospeccao_requisitos"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresaterceira",
            name="bairro",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="empresaterceira",
            name="cep",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="empresaterceira",
            name="estado",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="empresaterceira",
            name="municipio",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="empresaterceira",
            name="numero",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="empresaterceira",
            name="informacoes_bancarias",
            field=models.TextField(max_length=200),
        ),
    ]
