# Generated by Django 5.2 on 2025-09-22 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "gestao_contratos",
            "0022_empresaterceira_bairro_empresaterceira_cep_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitacaoprospeccao",
            name="aprovacao_fornecedor_gerente",
            field=models.CharField(
                choices=[
                    ("pendente", "Pendente"),
                    ("aprovado", "Aprovado"),
                    ("reprovado", "Reprovado"),
                ],
                default="pendente",
                max_length=20,
            ),
        ),
    ]
