# Generated by Django 5.2 on 2025-09-23 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestao_contratos", "0023_solicitacaoprospeccao_aprovacao_fornecedor_gerente"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitacaoprospeccao",
            name="aprocacao_fornecedor_gerente_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
