# Generated by Django 5.2 on 2025-09-24 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "gestao_contratos",
            "0024_solicitacaoprospeccao_aprocacao_fornecedor_gerente_em",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitacaoprospeccao",
            name="cronograma",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="cronograma/",
                verbose_name="Inserir cronograma",
            ),
        ),
    ]
