# Generated by Django 5.2 on 2025-09-25 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestao_contratos", "0025_solicitacaoprospeccao_cronograma"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contratoterceiros",
            name="proposta",
        ),
        migrations.AddField(
            model_name="contratoterceiros",
            name="prospeccao",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="gestao_contratos.solicitacaoprospeccao",
            ),
        ),
        migrations.AddField(
            model_name="documentobm",
            name="status_coordenador",
            field=models.CharField(
                choices=[
                    ("pendente", "Pendente"),
                    ("aprovado", "Aprovado"),
                    ("reprovado", "Reprovado"),
                ],
                default="pendente",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="documentobm",
            name="status_gerente",
            field=models.CharField(
                choices=[
                    ("pendente", "Pendente"),
                    ("aprovado", "Aprovado"),
                    ("reprovado", "Reprovado"),
                ],
                default="pendente",
                max_length=20,
            ),
        ),
    ]
