# Generated by Django 5.2 on 2025-09-25 12:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestao_contratos", "0026_remove_contratoterceiros_proposta_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentobm",
            name="data_aprovacao_coordenador",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 9, 25, 12, 5, 6, 33556, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="documentobm",
            name="data_aprovacao_gerente",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 9, 25, 12, 5, 28, 570743, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
    ]
