# Generated by Django 5.2 on 2025-09-29 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestao_contratos", "0027_documentobm_data_aprovacao_coordenador_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "arquivo",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="produto_do_fornecedor/",
                        verbose_name="Inserir arquivo para comprovação de entrega",
                    ),
                ),
                ("descricao", models.TextField()),
                ("justificativa", models.TextField(blank=True, null=True)),
                (
                    "avaliacao",
                    models.CharField(
                        blank=True,
                        choices=[("Aprovado", "Aprovado"), ("Reprovado", "Reprovado")],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("data_prevista", models.DateField(blank=True, null=True)),
                ("data_entrega", models.DateField(auto_now_add=True)),
                ("realizado", models.BooleanField(default=False)),
                ("com_atraso", models.BooleanField(default=False)),
                (
                    "valor_previsto",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "valor_pago",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contrato_terceiro",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestao_contratos.contratoterceiros",
                    ),
                ),
                (
                    "empresa_terceira",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestao_contratos.empresaterceira",
                    ),
                ),
                (
                    "prospeccao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestao_contratos.solicitacaoprospeccao",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="EntregaFornecedor",
        ),
    ]
