# Generated by Django 5.2 on 2025-09-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestao_contratos", "0028_evento_delete_entregafornecedor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evento",
            name="data_entrega",
            field=models.DateField(blank=True, null=True),
        ),
    ]
