# Generated by Django 5.2 on 2025-09-30 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestao_contratos", "0029_alter_evento_data_entrega"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentobm",
            name="data_aprovacao_coordenador",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="documentobm",
            name="data_aprovacao_gerente",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
