# Generated by Django 5.2 on 2025-09-30 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "gestao_contratos",
            "0030_alter_documentobm_data_aprovacao_coordenador_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="contratoterceiros",
            name="data_fim",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contratoterceiros",
            name="data_inicio",
            field=models.DateField(blank=True, null=True),
        ),
    ]
