# Generated by Django 5.2 on 2025-10-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestao_contratos", "0031_alter_contratoterceiros_data_fim_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contrato",
            name="data_fim",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="data_inicio",
            field=models.DateField(blank=True, null=True),
        ),
    ]
