# Generated by Django 5.2 on 2025-10-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestao_contratos", "0032_alter_contrato_data_fim_alter_contrato_data_inicio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contratoterceiros",
            name="valor_total",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
