# Generated by Django 5.2 on 2025-10-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestao_contratos", "0033_alter_contratoterceiros_valor_total"),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="data_pagamento",
            field=models.DateField(blank=True, null=True),
        ),
    ]
