# Generated by Django 5.2 on 2025-10-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestao_contratos", "0034_evento_data_pagamento"),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="data_prevista_pagamento",
            field=models.DateField(blank=True, null=True),
        ),
    ]
