# Generated by Django 5.2 on 2025-10-06 19:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestao_contratos", "0035_evento_data_prevista_pagamento"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarioPagamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_pagamento", models.DateField(unique=True)),
            ],
        ),
    ]
