# Generated by Django 5.2 on 2025-10-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestao_contratos", "0036_calendariopagamento"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contratotimelineterceiro",
            name="contrato",
        ),
        migrations.AddField(
            model_name="contratoterceiros",
            name="observacao",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="evento",
            name="observacao",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="ContratoTimeline",
        ),
        migrations.DeleteModel(
            name="ContratoTimelineTerceiro",
        ),
    ]
