# Generated by Django 5.2 on 2025-10-13 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestao_contratos", "0037_remove_contratotimelineterceiro_contrato_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contrato",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contratos",
                to="gestao_contratos.cliente",
            ),
        ),
        migrations.AlterField(
            model_name="contratoterceiros",
            name="empresa_terceira",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contratos",
                to="gestao_contratos.empresaterceira",
            ),
        ),
    ]
