# Generated by Django 5.2 on 2025-10-14 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "gestao_contratos",
            "0039_bm_observacao_calendariopagamento_observacao_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="email_focal",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="email_focal2",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="ponto_focal",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="ponto_focal2",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="telefone_focal",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="telefone_focal2",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
