# Generated by Django 5.2 on 2025-10-15 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestao_contratos", "0040_cliente_email_focal_cliente_email_focal2_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cliente",
            name="email_focal2",
        ),
        migrations.RemoveField(
            model_name="cliente",
            name="ponto_focal2",
        ),
        migrations.RemoveField(
            model_name="cliente",
            name="telefone_focal2",
        ),
        migrations.AddField(
            model_name="contratoterceiros",
            name="num_contrato",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="contratoterceiros",
            name="num_contrato_arquivo",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="contrato_do_fornecedor/",
                verbose_name="Inserir arquivo do contrato com fornecedor",
            ),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="status",
            field=models.CharField(
                choices=[
                    ("em_elaboracao", "Em elaboração"),
                    ("aguardando_assinatura", "Aguardando assinatura"),
                    ("ativo", "Ativo"),
                    ("suspenso", "Suspenso"),
                    ("encerrado", "Encerrado"),
                ],
                default="Em elaboracao",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="contratoterceiros",
            name="status",
            field=models.CharField(
                choices=[
                    ("em_elaboracao", "Em elaboração"),
                    ("aguardando_assinatura", "Aguardando assinatura"),
                    ("ativo", "Ativo"),
                    ("suspenso", "Suspenso"),
                    ("encerrado", "Encerrado"),
                ],
                default="Em elaboracao",
                max_length=30,
            ),
        ),
    ]
