# Generated by Django 5.2 on 2025-10-21 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestao_contratos", "0041_remove_cliente_email_focal2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bm",
            name="evento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="boletins_medicao",
                to="gestao_contratos.evento",
            ),
        ),
    ]
