# Generated by Django 5.2 on 2025-10-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestao_contratos", "0042_bm_evento"),
    ]

    operations = [
        migrations.AddField(
            model_name="contratoterceiros",
            name="condicao_pagamento",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
