# Generated by Django 5.2 on 2025-10-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestao_contratos", "0043_contratoterceiros_condicao_pagamento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contratoterceiros",
            name="condicao_pagamento",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
