# Generated by Django 5.2 on 2025-10-23 19:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestao_contratos", "0044_alter_contratoterceiros_condicao_pagamento"),
    ]

    operations = [
        migrations.AddField(
            model_name="bm",
            name="data_final_medicao",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bm",
            name="data_inicial_medicao",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
