# Generated by Django 5.2 on 2025-10-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestao_contratos", "0045_bm_data_final_medicao_bm_data_inicial_medicao"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aditivoterceiro",
            name="contrato",
        ),
        migrations.RemoveField(
            model_name="solicitacaocontratacaoterceiro",
            name="cod_projeto",
        ),
        migrations.RemoveField(
            model_name="solicitacaocontratacaoterceiro",
            name="empresa_1",
        ),
        migrations.RemoveField(
            model_name="solicitacaocontratacaoterceiro",
            name="empresa_2",
        ),
        migrations.RemoveField(
            model_name="solicitacaocontratacaoterceiro",
            name="empresa_3",
        ),
        migrations.RemoveField(
            model_name="solicitacaocontratacaoterceiro",
            name="numero_proposta_1",
        ),
        migrations.RemoveField(
            model_name="solicitacaocontratacaoterceiro",
            name="numero_proposta_2",
        ),
        migrations.RemoveField(
            model_name="solicitacaocontratacaoterceiro",
            name="numero_proposta_3",
        ),
        migrations.RemoveField(
            model_name="solicitacaocontratacaoterceiro",
            name="responsavel_sumprimento",
        ),
        migrations.RemoveField(
            model_name="solicitacaocontratacaoterceiro",
            name="solicitante_nome",
        ),
        migrations.AddField(
            model_name="contratoterceiros",
            name="guarda_chuva",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="documentocontratoterceiro",
            name="observacao",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="solicitacaoprospeccao",
            name="guarda_chuva",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.DeleteModel(
            name="Aditivo",
        ),
        migrations.DeleteModel(
            name="AditivoTerceiro",
        ),
        migrations.DeleteModel(
            name="SolicitacaoContratacaoTerceiro",
        ),
    ]
