# Generated by Django 5.2 on 2025-10-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestao_contratos", "0046_remove_aditivoterceiro_contrato_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bm",
            name="data_aprovacao_coordenador",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bm",
            name="data_aprovacao_gerente",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bm",
            name="status_coordenador",
            field=models.CharField(
                choices=[
                    ("pendente", "Pendente"),
                    ("aprovado", "Aprovado"),
                    ("reprovado", "Reprovado"),
                ],
                default="pendente",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="bm",
            name="status_gerente",
            field=models.CharField(
                choices=[
                    ("pendente", "Pendente"),
                    ("aprovado", "Aprovado"),
                    ("reprovado", "Reprovado"),
                ],
                default="pendente",
                max_length=20,
            ),
        ),
    ]
