# Generated by Django 5.2 on 2025-11-06 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestao_contratos", "0047_bm_data_aprovacao_coordenador_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="razao_social",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="documentobm",
            name="solicitacao",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="minuta_boletins_medicao",
                to="gestao_contratos.solicitacaoprospeccao",
            ),
        ),
    ]
