# Generated by Django 5.2 on 2025-11-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestao_contratos", "0048_cliente_razao_social_alter_documentobm_solicitacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitacaoprospeccao",
            name="justificativa_fornecedor_escolhido",
            field=models.TextField(blank=True, null=True),
        ),
    ]
