# Generated by Django 5.2 on 2025-11-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "gestao_contratos",
            "0049_solicitacaoprospeccao_justificativa_fornecedor_escolhido",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="bm",
            name="justificativa_reprovacao_coordenador",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Justificativa da Reprovação do Coordenador",
            ),
        ),
        migrations.AddField(
            model_name="bm",
            name="justificativa_reprovacao_gerente",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Justificativa da Reprovação do Gerente",
            ),
        ),
    ]
