# Generated by Django 5.2 on 2025-11-19 13:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestao_contratos", "0050_bm_justificativa_reprovacao_coordenador_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor_pago",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("parcela_paga", models.PositiveIntegerField()),
                ("data_pagamento", models.DateField(default=django.utils.timezone.now)),
                (
                    "arquivo_nf",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="NF/",
                        verbose_name="Inserir arquivo da Nota Fiscal",
                    ),
                ),
                ("observacao", models.TextField(blank=True, null=True)),
                (
                    "bm",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nota_fiscal",
                        to="gestao_contratos.bm",
                    ),
                ),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nota_fiscal",
                        to="gestao_contratos.contratoterceiros",
                    ),
                ),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nota_fiscal",
                        to="gestao_contratos.evento",
                    ),
                ),
            ],
        ),
    ]
