# Generated by Django 5.2 on 2025-11-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestao_contratos", "0051_nf"),
    ]

    operations = [
        migrations.AddField(
            model_name="nf",
            name="financeiro_autorizou",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="nf",
            name="nf_dentro_prazo",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="nf",
            name="arquivo_nf",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="NF/Fornecedor/",
                verbose_name="Inserir arquivo da Nota Fiscal",
            ),
        ),
    ]
