# Generated by Django 5.2 on 2025-11-20 19:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "gestao_contratos",
            "0052_nf_financeiro_autorizou_nf_nf_dentro_prazo_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="avaliacaofornecedor",
            name="nota",
        ),
        migrations.AddField(
            model_name="avaliacaofornecedor",
            name="avaliador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="avaliacaofornecedor",
            name="evento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="avaliacoes",
                to="gestao_contratos.evento",
            ),
        ),
        migrations.AddField(
            model_name="avaliacaofornecedor",
            name="nota_entrega",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AddField(
            model_name="avaliacaofornecedor",
            name="nota_gestao",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AddField(
            model_name="avaliacaofornecedor",
            name="nota_tecnica",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
