# Generated by Django 5.2 on 2025-12-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestao_contratos", "0053_remove_avaliacaofornecedor_nota_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="caminho_evidencia",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
