# Generated by Django 5.2 on 2025-12-02 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestao_contratos", "0054_evento_caminho_evidencia"),
    ]

    operations = [
        migrations.AddField(
            model_name="bm",
            name="aprovacao_pagamento",
            field=models.CharField(
                choices=[
                    ("pendente", "Pendente"),
                    ("aprovado", "Aprovado"),
                    ("reprovado", "Reprovado"),
                ],
                default="pendente",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="bm",
            name="data_aprovacao_diretor",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bm",
            name="justificativa_reprovacao_diretor",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Justificativa da Reprovação da Direção",
            ),
        ),
        
    ]
