# Generated by Django 5.2 on 2025-12-02 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "gestao_contratos",
            "0055_bm_aprovacao_pagamento_bm_data_aprovacao_diretor_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="evento",
            name="empresa_terceira",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="gestao_contratos.empresaterceira",
            ),
        ),
    ]
