# Generated by Django 5.2 on 2025-12-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestao_contratos", "0056_alter_evento_empresa_terceira"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evento",
            name="caminho_evidencia",
            field=models.CharField(blank=True, max_length=260, null=True),
        ),
    ]
