# Generated by Django 5.2 on 2025-12-04 14:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gestao_contratos", "0059_nfcliente_inserido_por"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nfcliente",
            name="financeiro_autorizou",
        ),
    ]
