# Generated by Django 5.2 on 2025-12-10 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestao_contratos", "0060_remove_nfcliente_financeiro_autorizou"),
    ]

    operations = [
        migrations.AddField(
            model_name="contrato",
            name="lider_contrato",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"grupo": "lider_contrato"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contratos_liderados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contratoterceiros",
            name="lider_contrato",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"grupo": "lider_contrato"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contratos_liderados_terceiros",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="solicitacaoprospeccao",
            name="lider_contrato",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"grupo": "lider_contrato"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="solicitacoes_lideradas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="grupo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("coordenador", "Coordenador de Contrato"),
                    ("lider_contrato", "Lider de Contratos"),
                    ("gerente", "Gerente"),
                    ("gerente_contrato", "Gerente de Contratos"),
                    ("diretoria", "Diretoria"),
                    ("financeiro", "Financeiro"),
                    ("suprimento", "Suprimento"),
                    ("fornecedor", "Fornecedor"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
