# Generated by Django 5.2 on 2025-12-23 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestao_contratos", "0061_contrato_lider_contrato_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrdemServico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                (
                    "valor_previsto",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("prazo_execucao", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("rascunho", "Rascunho"),
                            ("pendente_lider", "Pendente Líder"),
                            ("pendente_gerente", "Pendente Gerente"),
                            ("pendente_suprimento", "Pendente Suprimento"),
                            ("aprovada", "Aprovada"),
                            ("reprovada", "Reprovada"),
                            ("finalizada", "Finalizada"),
                        ],
                        default="rascunho",
                        max_length=30,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "contrato",
                    models.ForeignKey(
                        limit_choices_to={"guarda_chuva": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ordens_servico",
                        to="gestao_contratos.contratoterceiros",
                    ),
                ),
                (
                    "lider_contrato",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"grupo": "lider_contrato"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ordens_liderados_terceiros",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "solicitante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ordens_solicitantes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
