# Generated by Django 5.2 on 2025-12-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestao_contratos", "0062_ordemservico"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordemservico",
            name="aprovacao_lider",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="ordemservico",
            name="aprovado_lider_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
