# Generated by Django 5.2 on 2025-12-23 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestao_contratos", "0063_ordemservico_aprovacao_lider_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordemservico",
            name="arquivo_os",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="OS/",
                verbose_name="Inserir arquivo da Ordem de Serviço",
            ),
        ),
    ]
