# Generated by Django 5.2 on 2025-12-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestao_contratos", "0064_ordemservico_arquivo_os"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordemservico",
            name="aprovacao_gerente",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="ordemservico",
            name="aprovado_gerente_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
