# Generated by Django 5.2 on 2025-12-23 20:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestao_contratos", "0065_ordemservico_aprovacao_gerente_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordemservico",
            name="justificativa_reprovacao_gerente",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ordemservico",
            name="justificativa_reprovacao_lider",
            field=models.TextField(blank=True, null=True),
        ),
    ]
