# Generated by Django 5.2 on 2025-12-24 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "gestao_contratos",
            "0066_ordemservico_justificativa_reprovacao_gerente_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="ordemservico",
            name="cod_projeto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="gestao_contratos.contrato",
            ),
        ),
        migrations.AlterField(
            model_name="ordemservico",
            name="status",
            field=models.CharField(
                choices=[
                    ("solicitacao_os", "Solicitação de OS"),
                    ("pendente_lider", "Pendente Líder"),
                    ("pendente_gerente", "Pendente Gerente"),
                    ("pendente_suprimento", "Pendente Suprimento"),
                    ("aprovada", "Aprovada"),
                    ("reprovada", "Reprovada"),
                    ("finalizada", "Finalizada"),
                ],
                default="solicitacao_os",
                max_length=30,
            ),
        ),
    ]
