# Generated by Django 5.2 on 2025-12-24 13:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gestao_contratos", "0067_ordemservico_cod_projeto_alter_ordemservico_status"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="OrdemServico",
            new_name="SolicitacaoOrdemServico",
        ),
    ]
