# Generated by Django 5.2 on 2025-12-24 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestao_contratos", "0068_rename_ordemservico_solicitacaoordemservico"),
    ]

    operations = [
        migrations.CreateModel(
            name="OS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                (
                    "valor",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("prazo_execucao", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("em_execucao", "Em Execução"),
                            ("paralizada", "Paralizada"),
                            ("cancelada", "Cancelada"),
                            ("finalizada", "Finalizada"),
                        ],
                        default="em_execucao",
                        max_length=30,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "arquivo_os",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="OS/",
                        verbose_name="Inserir arquivo da Ordem de Serviço",
                    ),
                ),
                (
                    "cod_projeto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestao_contratos.contrato",
                    ),
                ),
                (
                    "contrato",
                    models.ForeignKey(
                        limit_choices_to={"guarda_chuva": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="os_cadastrada",
                        to="gestao_contratos.contratoterceiros",
                    ),
                ),
                (
                    "coordenador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ordens_coordenador",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lider_contrato",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"grupo": "lider_contrato"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ordens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
