# Generated by Django 5.2 on 2025-12-24 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestao_contratos", "0069_os"),
    ]

    operations = [
        migrations.AddField(
            model_name="os",
            name="solicitacao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="gestao_contratos.solicitacaoordemservico",
            ),
        ),
    ]
