# Generated by Django 5.2 on 2025-12-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestao_contratos", "0070_os_solicitacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="os",
            name="avaliacao",
            field=models.CharField(
                blank=True,
                choices=[("Aprovado", "Aprovado"), ("Reprovado", "Reprovado")],
                max_length=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="os",
            name="caminho_evidencia",
            field=models.CharField(blank=True, max_length=260, null=True),
        ),
        migrations.AddField(
            model_name="os",
            name="com_atraso",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="os",
            name="data_entrega",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="os",
            name="data_pagamento",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="os",
            name="observacao",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="os",
            name="realizado",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="os",
            name="valor_pago",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
