# Generated by Django 5.2 on 2026-02-04 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "gestao_contratos",
            "0071_os_avaliacao_os_caminho_evidencia_os_com_atraso_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="SolicitacaoContrato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.TextField(blank=True, null=True)),
                ("requisitos", models.TextField(blank=True, null=True)),
                ("previsto_no_orcamento", models.BooleanField(default=False)),
                (
                    "valor_provisionado",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "valor_vendido",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("data_solicitacao", models.DateTimeField(auto_now_add=True)),
                (
                    "guarda_chuva",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "cronograma",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="cronograma/",
                        verbose_name="Inserir cronograma",
                    ),
                ),
                (
                    "aprovacao_fornecedor_gerente",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("aprovado", "Aprovado"),
                            ("reprovado", "Reprovado"),
                        ],
                        default="pendente",
                        max_length=20,
                    ),
                ),
                (
                    "aprocacao_fornecedor_gerente_em",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "aprovacao_fornecedor_diretor",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("aprovado", "Aprovado"),
                            ("reprovado", "Reprovado"),
                        ],
                        default="pendente",
                        max_length=20,
                    ),
                ),
                (
                    "aprocacao_fornecedor_diretor_em",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("aprovacao_gerencia", models.BooleanField(default=False)),
                ("reprovacao_gerencia", models.BooleanField(default=False)),
                ("aprovacao_diretoria", models.BooleanField(default=False)),
                ("reprovacao_diretoria", models.BooleanField(default=False)),
                ("justificativa_gerencia", models.TextField(blank=True, null=True)),
                ("justificativa_diretoria", models.TextField(blank=True, null=True)),
                (
                    "acao_gerencia",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("renegociar_valor", "Renegociar Valor"),
                            ("renegociar_prazo", "Renegociar Prazo"),
                            ("alterar_fornecedor", "Selecionar outro Fornecedor"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "acao_diretoria",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("renegociar_valor", "Renegociar Valor"),
                            ("renegociar_prazo", "Renegociar Prazo"),
                            ("alterar_fornecedor", "Selecionar outro Fornecedor"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("observacao", models.TextField(blank=True, null=True)),
                (
                    "justificativa_fornecedor_escolhido",
                    models.TextField(blank=True, null=True),
                ),
                ("status", models.CharField(default="Em análise", max_length=100)),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solicitacoes_contratos",
                        to="gestao_contratos.contrato",
                    ),
                ),
                (
                    "coordenador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fornecedor_escolhido",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="escolhido_contrato",
                        to="gestao_contratos.empresaterceira",
                    ),
                ),
                (
                    "lider_contrato",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"grupo": "lider_contrato"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="solicitacoes_lideradas_contratos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
