# Generated by Django 5.2 on 2026-02-05 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestao_contratos", "0072_solicitacaocontrato"),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="solicitacao_contrato",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="gestao_contratos.solicitacaocontrato",
            ),
        ),
        migrations.AlterField(
            model_name="solicitacaocontrato",
            name="lider_contrato",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"grupo__in": ["lider_contrato", "gerente_contrato"]},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="solicitacoes_lideradas_contratos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
