# Generated by Django 5.2 on 2026-02-06 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestao_contratos", "0073_evento_solicitacao_contrato_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentobm",
            name="solicitacao_contrato",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="minuta_boletins_medicao_contrato",
                to="gestao_contratos.solicitacaoprospeccao",
            ),
        ),
        migrations.AlterField(
            model_name="documentobm",
            name="solicitacao",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="minuta_boletins_medicao",
                to="gestao_contratos.solicitacaoprospeccao",
            ),
        ),
    ]
