# Generated by Django 5.2 on 2026-02-06 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestao_contratos", "0075_alter_documentobm_solicitacao_contrato"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentocontratoterceiro",
            name="solicitacao_contrato",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="minuta_contrato",
                to="gestao_contratos.solicitacaocontrato",
            ),
        ),
        migrations.AlterField(
            model_name="documentocontratoterceiro",
            name="solicitacao",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contrato_relacionado",
                to="gestao_contratos.solicitacaoprospeccao",
            ),
        ),
    ]
