# Generated by Django 5.2 on 2026-02-09 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "gestao_contratos",
            "0076_documentocontratoterceiro_solicitacao_contrato_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="propostafornecedor",
            name="solicitacao_contrato",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proposta",
                to="gestao_contratos.solicitacaocontrato",
            ),
        ),
        migrations.AlterField(
            model_name="propostafornecedor",
            name="solicitacao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="propostas",
                to="gestao_contratos.solicitacaoprospeccao",
            ),
        ),
    ]
