# Generated by Django 5.2 on 2026-02-09 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestao_contratos", "0077_propostafornecedor_solicitacao_contrato_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contratoterceiros",
            name="solicitacao",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="gestao_contratos.solicitacaocontrato",
            ),
        ),
    ]
