# Generated by Django 5.2 on 2026-02-13 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestao_contratos", "0078_contratoterceiros_solicitacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitacaoprospeccao",
            name="aprocacao_fornecedor_diretor_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="solicitacaoprospeccao",
            name="aprovacao_fornecedor_diretor",
            field=models.CharField(
                choices=[
                    ("pendente", "Pendente"),
                    ("aprovado", "Aprovado"),
                    ("reprovado", "Reprovado"),
                ],
                default="pendente",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="solicitacaoprospeccao",
            name="lider_contrato",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"grupo__in": ["lider_contrato", "gerente_contrato"]},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="solicitacoes_lideradas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
