# Generated by Django 5.2 on 2026-02-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "gestao_contratos",
            "0079_solicitacaoprospeccao_aprocacao_fornecedor_diretor_em_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitacaocontrato",
            name="justificativa_solicitacao",
            field=models.TextField(blank=True, null=True),
        ),
    ]
