# Generated by Django 5.2 on 2026-03-02 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestao_contratos", "0080_solicitacaocontrato_justificativa_solicitacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitacaocontrato",
            name="data_fim",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="solicitacaocontrato",
            name="data_inicio",
            field=models.DateField(blank=True, null=True),
        ),
    ]
