# Generated by Django 5.2 on 2026-03-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestao_contratos", "0081_solicitacaocontrato_data_fim_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documentobm",
            name="assinatura_fornecedor",
        ),
        migrations.RemoveField(
            model_name="documentobm",
            name="assinatura_gerente",
        ),
        migrations.AlterField(
            model_name="user",
            name="grupo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("coordenador", "Coordenador de Contrato"),
                    ("lider_contrato", "Lider de Contratos"),
                    ("gerente", "Gerente"),
                    ("gerente_lider", "Gerente e Lider de Contratos"),
                    ("gerente_contrato", "Gerente de Contratos"),
                    ("diretoria", "Diretoria"),
                    ("financeiro", "Financeiro"),
                    ("suprimento", "Suprimento"),
                    ("fornecedor", "Fornecedor"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
