# Generated by Django 5.2 on 2026-03-20 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestao_contratos", "0082_remove_documentobm_assinatura_fornecedor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitacaocontrato",
            name="forma_pagamento",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[(30, "30 dias"), (60, "60 dias"), (90, "90 dias")],
                null=True,
                verbose_name="Forma de Pagamento (dias)",
            ),
        ),
        migrations.AddField(
            model_name="solicitacaocontrato",
            name="valor_disponivel",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="solicitacaoordemservico",
            name="lider_contrato",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={
                    "grupo__in": ["lider_contrato", "gerente_lider", "gerente_contrato"]
                },
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ordens_liderados_terceiros",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
