# Generated by Django 5.2 on 2026-03-20 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestao_contratos", "0083_solicitacaocontrato_forma_pagamento_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitacaoprospeccao",
            name="forma_pagamento",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[(30, "30 dias"), (60, "60 dias"), (90, "90 dias")],
                null=True,
                verbose_name="Forma de Pagamento (dias)",
            ),
        ),
        migrations.AddField(
            model_name="solicitacaoprospeccao",
            name="valor_disponivel",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="solicitacaocontrato",
            name="coordenador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="solicitacaoprospeccao",
            name="coordenador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
