# Generated by Django 5.2 on 2026-03-20 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestao_contratos", "0084_solicitacaoprospeccao_forma_pagamento_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitacaocontrato",
            name="justificativa_orcamento",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="solicitacaoprospeccao",
            name="justificativa_orcamento",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="solicitacaoprospeccao",
            name="lider_contrato",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={
                    "grupo__in": ["lider_contrato", "gerente_contrato", "gerente_lider"]
                },
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="solicitacoes_lideradas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
