# Generated by Django 5.2 on 2026-03-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestao_contratos", "0086_alter_contrato_coordenador_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contrato",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("em_elaboracao", "Em elaboração"),
                    ("aguardando_assinatura", "Aguardando assinatura"),
                    ("ativo", "Ativo"),
                    ("suspenso", "Suspenso"),
                    ("encerrado", "Encerrado"),
                ],
                default="Em elaboracao",
                max_length=30,
                null=True,
            ),
        ),
    ]
