# Generated by Django 5.2 on 2026-03-24 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestao_contratos", "0088_alter_contrato_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solicitacaocontrato",
            name="contrato",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="solicitacoes_contratos",
                to="gestao_contratos.contrato",
            ),
        ),
    ]
