# Generated by Django 5.2 on 2026-03-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestao_contratos", "0089_alter_solicitacaocontrato_contrato"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitacaocontrato",
            name="solicitante",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
