# Generated by Django 5.2 on 2026-03-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestao_contratos", "0090_solicitacaocontrato_solicitante"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitacaoprospeccao",
            name="solicitante",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
