# Generated by Django 5.2 on 2026-03-24 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestao_contratos", "0091_solicitacaoprospeccao_solicitante"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contratoterceiros",
            name="cod_projeto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="gestao_contratos.contrato",
            ),
        ),
        migrations.AlterField(
            model_name="contratoterceiros",
            name="lider_contrato",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={
                    "grupo__in": ["lider_contrato", "gerente_contrato", "gerente_lider"]
                },
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contratos_liderados_terceiros",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="solicitacaocontrato",
            name="lider_contrato",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={
                    "grupo__in": ["lider_contrato", "gerente_contrato", "gerente_lider"]
                },
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="solicitacoes_lideradas_contratos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
