# Generated by Django 5.2 on 2026-03-26 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestao_contratos", "0092_alter_contratoterceiros_cod_projeto_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitacaoprospeccao",
            name="data_fim",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="solicitacaoprospeccao",
            name="data_inicio",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="solicitacaoprospeccao",
            name="justificativa_solicitacao",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="lider_contrato",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={
                    "grupo__in": ["lider_contrato", "gerente_contrato", "gerente_lider"]
                },
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contratos_liderados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="os",
            name="lider_contrato",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={
                    "grupo__in": ["lider_contrato", "gerente_contrato", "gerente_lider"]
                },
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ordens",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
