# Generated by Django 5.2 on 2026-03-27 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestao_contratos", "0093_solicitacaoprospeccao_data_fim_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitacaoordemservico",
            name="coordenador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="os_coordenados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
