# Generated by Django 5.2 on 2026-03-27 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestao_contratos", "0094_solicitacaoordemservico_coordenador"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitacaoordemservico",
            name="aprovacao_diretor",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="solicitacaoordemservico",
            name="aprovado_diretor_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="solicitacaoordemservico",
            name="justificativa_reprovacao_diretor",
            field=models.TextField(blank=True, null=True),
        ),
    ]
