# Generated by Django 5.2 on 2026-04-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestao_contratos", "0096_registroauditoria"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contratoterceiros",
            name="status",
            field=models.CharField(
                choices=[
                    ("em_elaboracao", "Em elaboração"),
                    ("aguardando_assinatura", "Aguardando assinatura"),
                    ("ativo", "Ativo"),
                    ("suspenso", "Suspenso"),
                    ("encerrado", "Encerrado"),
                ],
                default="em_elaboracao",
                max_length=30,
            ),
        ),
    ]
