# Generated by Django 5.2 on 2026-04-28 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_contratos', '0097_alter_contratoterceiros_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AditivoContratoTerceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('valor_total_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('novo_valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('data_fim_anterior', models.DateField(blank=True, null=True)),
                ('nova_data_fim', models.DateField(blank=True, null=True)),
                ('arquivo_aditivo', models.FileField(blank=True, null=True, upload_to='aditivos_fornecedor/')),
                ('documento_enviado_em', models.DateTimeField(blank=True, null=True)),
                ('status_lider', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], default='pendente', max_length=20)),
                ('data_aprovacao_lider', models.DateTimeField(blank=True, null=True)),
                ('justificativa_reprovacao_lider', models.TextField(blank=True, null=True)),
                ('status_gerente', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], default='pendente', max_length=20)),
                ('data_aprovacao_gerente', models.DateTimeField(blank=True, null=True)),
                ('justificativa_reprovacao_gerente', models.TextField(blank=True, null=True)),
                ('status_diretoria', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], default='pendente', max_length=20)),
                ('data_aprovacao_diretoria', models.DateTimeField(blank=True, null=True)),
                ('justificativa_reprovacao_diretoria', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aditivos', to='gestao_contratos.contratoterceiros')),
                ('documento_enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aditivos_enviados_terceiros', to=settings.AUTH_USER_MODEL)),
                ('solicitado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aditivos_solicitados_terceiros', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
