# Generated by Django 5.2 on 2026-04-28 18:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_contratos', '0098_aditivocontratoterceiro'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='coordenadores',
            field=models.ManyToManyField(blank=True, limit_choices_to={'grupo': 'coordenador'}, related_name='contratos_cliente_como_coordenador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contratoterceiros',
            name='coordenadores',
            field=models.ManyToManyField(blank=True, limit_choices_to={'grupo': 'coordenador'}, related_name='contratos_fornecedor_como_coordenador', to=settings.AUTH_USER_MODEL),
        ),
    ]
