# Generated by Django 5.2 on 2026-05-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_contratos', '0099_contrato_coordenadores_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentobm',
            name='minuta_boletim_assinado',
            field=models.FileField(blank=True, null=True, upload_to='Minuta boletim/assinados/'),
        ),
        migrations.AddField(
            model_name='documentocontratoterceiro',
            name='arquivo_contrato_assinado',
            field=models.FileField(blank=True, null=True, upload_to='contratos/assinados/', verbose_name='Contrato assinado em PDF'),
        ),
    ]
