# Generated by Django 5.2 on 2026-05-05 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_contratos', '0100_documentobm_minuta_boletim_assinado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aditivocontratoterceiro',
            name='arquivo_aditivo_assinado',
            field=models.FileField(blank=True, null=True, upload_to='aditivos_fornecedor_assinados/'),
        ),
        migrations.AddField(
            model_name='aditivocontratoterceiro',
            name='documento_assinado_enviado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aditivocontratoterceiro',
            name='documento_assinado_enviado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aditivos_assinados_enviados_terceiros', to=settings.AUTH_USER_MODEL),
        ),
    ]
