# Generated by Django 5.2 on 2026-05-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_contratos', '0101_aditivocontratoterceiro_arquivo_aditivo_assinado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='complemento',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresaterceira',
            name='complemento',
            field=models.TextField(blank=True, null=True),
        ),
    ]
