# Generated by Django 5.2 on 2026-05-14 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_contratos', '0102_cliente_complemento_empresaterceira_complemento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='os',
            name='coordenador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_coordenador', to=settings.AUTH_USER_MODEL),
        ),
    ]
