# Generated by Django 5.2 on 2026-05-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_contratos', '0103_alter_os_coordenador'),
    ]

    operations = [
        migrations.AddField(
            model_name='os',
            name='data_prevista_pagamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitacaoordemservico',
            name='data_prevista_pagamento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
