# Generated by Django 5.2 on 2026-05-19 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_contratos', '0104_os_data_prevista_pagamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bm',
            name='os',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boletins_medicao', to='gestao_contratos.os'),
        ),
        migrations.AddField(
            model_name='nf',
            name='os',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nota_fiscal', to='gestao_contratos.os'),
        ),
        migrations.AlterField(
            model_name='nf',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nota_fiscal', to='gestao_contratos.evento'),
        ),
    ]
