# Generated by Django 5.2 on 2026-05-20 16:14

from django.db import migrations, models


def seed_default_sla_configuration(apps, schema_editor):
    ConfiguracaoSLA = apps.get_model('gestao_contratos', 'ConfiguracaoSLA')
    defaults = {
        'prospeccao': [
            ('solicitacao', 'Solicitacao de prospeccao', 1, 2),
            ('aprovacao_suprimento', 'Aprovacao do suprimento', 2, 2),
            ('triagem', 'Triagem', 3, 3),
            ('aprovacao_fornecedor', 'Aprovacao do fornecedor', 4, 3),
            ('planejamento_contrato', 'Planejamento do contrato', 5, 2),
            ('aprovacao_final', 'Aprovacao final', 6, 2),
            ('documento_assinado', 'Contrato assinado', 7, 5),
        ],
        'contratacao': [
            ('solicitacao', 'Solicitacao de contratacao', 1, 3),
            ('planejamento_contrato', 'Planejamento do contrato', 2, 2),
            ('aprovacao_final', 'Aprovacao final', 3, 2),
            ('documento_assinado', 'Contrato assinado', 4, 5),
        ],
        'os': [
            ('aprovacao_gerencia', 'Aprovacao da gerencia', 1, 2),
            ('aprovacao_diretoria', 'Aprovacao da diretoria', 2, 2),
            ('minuta_os', 'Minuta da OS', 3, 2),
            ('aprovacao_minuta', 'Aprovacao da minuta', 4, 2),
        ],
        'aditivo': [
            ('aprovacao_solicitacao', 'Aprovacao da solicitacao', 1, 2),
            ('minuta_aditivo', 'Minuta do aditivo', 2, 2),
            ('aprovacao_minuta', 'Aprovacao da minuta', 3, 2),
            ('documento_assinado', 'Documento assinado', 4, 3),
        ],
    }

    for tipo_fluxo, rows in defaults.items():
        for etapa, nome_etapa, ordem, prazo_dias_uteis in rows:
            ConfiguracaoSLA.objects.update_or_create(
                tipo_fluxo=tipo_fluxo,
                etapa=etapa,
                defaults={
                    'nome_etapa': nome_etapa,
                    'ordem': ordem,
                    'prazo_dias_uteis': prazo_dias_uteis,
                    'ativo': True,
                },
            )


def unseed_default_sla_configuration(apps, schema_editor):
    ConfiguracaoSLA = apps.get_model('gestao_contratos', 'ConfiguracaoSLA')
    ConfiguracaoSLA.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_contratos', '0105_bm_os_nf_os_alter_nf_evento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('data', models.DateField(unique=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Feriado',
                'verbose_name_plural': 'Feriados',
                'ordering': ['data', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoSLA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_fluxo', models.CharField(choices=[('prospeccao', 'Prospeccao'), ('contratacao', 'Contratacao'), ('aditivo', 'Aditivo'), ('os', 'Ordem de Servico')], max_length=30)),
                ('etapa', models.CharField(max_length=100)),
                ('nome_etapa', models.CharField(max_length=150)),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('prazo_dias_uteis', models.PositiveIntegerField(default=1)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuracao de SLA',
                'verbose_name_plural': 'Configuracoes de SLA',
                'ordering': ['tipo_fluxo', 'ordem', 'nome_etapa'],
                'unique_together': {('tipo_fluxo', 'etapa')},
            },
        ),
        migrations.RunPython(seed_default_sla_configuration, unseed_default_sla_configuration),
    ]
