# Generated by Django 5.2 on 2026-05-22 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_contratos', '0106_feriado_configuracaosla'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacaofornecedor',
            name='os',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='gestao_contratos.os'),
        ),
    ]
