# Generated by Django 5.2 on 2026-05-26 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_contratos', '0108_configuracaosla_bm'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='aditivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='gestao_contratos.aditivocontratoterceiro'),
        ),
    ]
