# Generated by Django 5.2 on 2026-05-27 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_contratos', '0110_user_gerente_contrato_ausente'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratoterceiros',
            name='ocultar_home_contrato_vencido',
            field=models.BooleanField(default=False),
        ),
    ]
