# Generated by Django 5.2 on 2026-07-20 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_contratos', '0113_solicitacaocontrato_proposta_tecnica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaocontrato',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('conforme_pagamento_cliente', 'Conforme Pagamento do Cliente'), ('conforme_medicao_aprovada', 'Conforme Medição Aprovada'), ('30', '30 dias'), ('60', '60 dias'), ('90', '90 dias')], max_length=40, null=True, verbose_name='Forma de Pagamento'),
        ),
        migrations.AlterField(
            model_name='solicitacaoprospeccao',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('conforme_pagamento_cliente', 'Conforme Pagamento do Cliente'), ('conforme_medicao_aprovada', 'Conforme Medição Aprovada'), ('30', '30 dias'), ('60', '60 dias'), ('90', '90 dias')], max_length=40, null=True, verbose_name='Forma de Pagamento'),
        ),
    ]
